### ISSUE TITLE
Auto refresh with Visual Studio

### ISSUE THREAD

**Issue by dsmeltz** [OfficeDev/microsoft-teams-app-quickstarts#33]
The VS Code version of this extension seems to auto refresh the *.zip files for deployment.  Is there any chance that VS 2019 could behave in the same manner?  It's sort of cumbersome have to restart the web server, just to get a markup or JavaScript change to show in my local Teams.

**Comment by asnow003** [comment]
The refreshing in VS Code is a part of webpack and its connection with your browser.  So when you make a code change in VS Code the "watcher" does a rebuild and sends a signal to your browser to refresh.

In VS is you are only making markup or JS changes we don't have the nice connection to your browser because the project at its core is C#/MVC.  What you could do though is hit the little refresh button in Teams which looks like a circle with an arrow.  That will do the same like you refresh the browser.

**Comment by dsmeltz** [comment]
Feel free to close.  I was modifying JS in a view file and not a *.js file.  That was really my problem.  Thanks for the help!
