### ISSUE TITLE
Hanging on generating scaffold for my app

### ISSUE THREAD

**Issue by SheilaAtKerr** [OfficeDev/microsoft-teams-app-quickstarts#37]
Issue Type: <b>Bug</b>

Create a new Teams app -> Bot -> create a new Bot or Use and existing bot registered with Bit Framework -> finish. The generating scaffold for my app never ends.

Extension version: 1.1.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (23.07GB free)|
|Process Argv|--crash-reporter-id e6ada007-8df9-4abd-ba0d-5d368516781c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SheilaAtKerr** [comment]
Tried local drive. It didn't help.

**Comment by asnow003** [comment]
I am in the process of creating an updated version 1.1.2 with some enhanced logging.  We got another report of your same issue but we are not able to repro.

Once I publish I will send a message here and if you could test it out that would be really helpful to get to the bottom of this issue.

**Comment by SheilaAtKerr** [comment]
Thanks for the quick response. When I tried my local drive D:. It didn't work. But it did create if I chose drive C:. However, it didn't create publish folder.

**Comment by CemAdg** [comment]
I have the same issue that it's not creating the publish folder

**Comment by DaehyunLee** [comment]
I'm experiencing the same thing. 
Is there any known workaround?

**Comment by SJaschinski** [comment]
Same issue here, no .publish folder generated during scaffolding.
Microsoft Teams Toolkit v1.1.1
Visual Studio Code 1.50.1
macOS Catalina 10.15.7

**Comment by asnow003** [comment]
There is an issue with choosing the root drive to create your app...try selecting or creating a folder at the root.  Also, in regards to the .publish folder.  This has been deprecated since its not code and just configuration.  You should use the "App Studio" tool in the toolkit to modify your configuration when needed.

Fix for the root drive issue coming soon!

**Comment by SJaschinski** [comment]
Figured out how to do it using App Studio. Problem is that all your Getting Started documentation is referring to the deprecated approach. Please make sure to update the docs as soon as possible. Frustrating experience if you try to walk through the very first sample and fail because you are not able to follow instructions. Other than that great tooling you provide for Visual Studio Code. Keep the good stuff coming!

**Comment by asnow003** [comment]
@SJaschinski thank you and so sorry about the documentation lets me get that updated ASAP!   Lots more tooling updates coming...  We are trying to iterate and improve so really sorry when things get out of sync... I will make sure I do better keeping the docs updated.

**Comment by ru1fdo** [comment]
> @SJaschinski thank you and so sorry about the documentation lets me get that updated ASAP! Lots more tooling updates coming... We are trying to iterate and improve so really sorry when things get out of sync... I will make sure I do better keeping the docs updated.

Looking forward to seeing the new guidance on this as I too am blocked as is @SJaschinski

**Comment by asnow003** [comment]
@ru1fdo  where are you blocked?  I can help you out if you are stuck on a certain part....let me know what type of project you are creating.  Tab, bot...etc?

**Comment by ru1fdo** [comment]
> @ru1fdo where are you blocked? I can help you out if you are stuck on a certain part....let me know what type of project you are creating. Tab, bot...etc?

I started the Hello, World app tutorial earlier today. The scaffolding is now working after switching to c:\<foldername> from d:\<otherfoldername>. 

https://docs.microsoft.com/en-us/microsoftteams/platform/build-your-first-app/build-and-run <= Step 3 works fine
Step 4 - ngrok is bound but where is the Development.env file now stored since the .publish folder is deprecated?

Happy to help with the documentation if you are swamped with dev work!

TIA

**Comment by asnow003** [comment]
The documentation is currently being updated and should be released in the next day or two....

In the step you no longer need to use ngrok for Tab apps and the hello world sample.  Please just follow the readme doc in the sample to get your app up and running.

**Comment by ru1fdo** [comment]
> The documentation is currently being updated and should be released in the next day or two....
> 
> In the step you no longer need to use ngrok for Tab apps and the hello world sample. Please just follow the readme doc in the sample to get your app up and running.

@asnow003 Thanks for the update. I was able to get the Hello World sample working!! I'll reach back out if the next examples have similar issues or if the actual work we're trying to do gets blocked. Thanks again..

**Comment by asnow003** [comment]
@ru1fdo that's great and thank you for testing everything out!  Feel free to open another issue in regards to any new things you come across.
